# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'version.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(452, 296)
        Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.commandLinkButton = QtWidgets.QCommandLinkButton(Frame)
        self.commandLinkButton.setGeometry(QtCore.QRect(20, 240, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.commandLinkButton.setFont(font)
        self.commandLinkButton.setIconSize(QtCore.QSize(25, 25))
        self.commandLinkButton.setCheckable(False)
        self.commandLinkButton.setDescription("")
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.pushButton = QtWidgets.QPushButton(Frame)
        self.pushButton.setGeometry(QtCore.QRect(280, 180, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(Frame)
        self.label_3.setGeometry(QtCore.QRect(30, 100, 171, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Frame)
        self.label_2.setGeometry(QtCore.QRect(340, 60, 81, 31))
        self.label_2.setObjectName("label_2")
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(Frame)
        self.commandLinkButton_2.setGeometry(QtCore.QRect(160, 240, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.commandLinkButton_2.setFont(font)
        self.commandLinkButton_2.setIconSize(QtCore.QSize(25, 25))
        self.commandLinkButton_2.setCheckable(False)
        self.commandLinkButton_2.setDescription("")
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.radioButton_2 = QtWidgets.QRadioButton(Frame)
        self.radioButton_2.setGeometry(QtCore.QRect(210, 150, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(100, 20, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(31)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.radioButton = QtWidgets.QRadioButton(Frame)
        self.radioButton.setGeometry(QtCore.QRect(210, 120, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.commandLinkButton_3 = QtWidgets.QCommandLinkButton(Frame)
        self.commandLinkButton_3.setGeometry(QtCore.QRect(290, 240, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.commandLinkButton_3.setFont(font)
        self.commandLinkButton_3.setIconSize(QtCore.QSize(25, 25))
        self.commandLinkButton_3.setCheckable(False)
        self.commandLinkButton_3.setDescription("")
        self.commandLinkButton_3.setObjectName("commandLinkButton_3")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.commandLinkButton.setText(_translate("Frame", "Facebook"))
        self.pushButton.setText(_translate("Frame", "Start"))
        self.label_3.setText(_translate("Frame", "Phiên bản / Version"))
        self.label_2.setText(_translate("Frame", "by NoName"))
        self.commandLinkButton_2.setText(_translate("Frame", "Google"))
        self.radioButton_2.setText(_translate("Frame", "English"))
        self.label.setText(_translate("Frame", "Đuổi hình bắt chữ"))
        self.radioButton.setText(_translate("Frame", "Tiếng Việt"))
        self.commandLinkButton_3.setText(_translate("Frame", "Twitter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
